docs/converters_endpoints.md
Related cards:
1 - https://trello.com/c/RkRShdOP/430-converters-change-userid-to-leafuserid
2 - https://trello.com/c/DtUKbcz2/432-converters-change-userid-to-leafuserid-in-postman-collection-and-docs
=> Changing userId to leafUserId

docs/operations_endpoints.md, docs/satellite_endpoints.md
changed list of params in GET Operations to a table for better visualization
changed a little bit of the information organization and flow on POST satellite and GET satellite images
=> Better formatting and organization

docs/field_boundaries_endpoints.md
Note this PR targets farm-docs, because it was merged from it.
=> Add two /growers endpoints

docs/crops.md, docs/field_boundaries_endpoints.md, docs/operations_endpoints.md
Pair PR at the postman repo [here](https://github.com/Leaf-Agriculture/Leaf-API-Postman-Collection/pull/27)
=> Add origin to the model of an Operation resource (Fields) and its filter param

docs/alerts_endpoints.md, docs/alerts_overview.md
=> Alerts release

docs/operations_density_table.md, docs/operations_endpoints.md
Adding the densities for most of our mapped crops
=> Add density table to docs

sidebars.js
Adding density table to the documentation sidebar
=> Add density table to sidebar

docs/converters_endpoints.md, docs/converters_overview.md
=> fixing links

docs/user_management_endpoints.md
Removed somar and climatempo references
from LeafUser endpoints
=> Removed somar and climatempo references

docs/beta_features_overview.md, docs/beta_machines_endpoints.md, sidebars.js
=> Add beta and machine information

docs/beta_features_overview.md, docs/beta_prescriptions_endpoints.md, sidebars.js
=> Add prescriptions documentation

docs/field_boundaries_endpoints.md
(cherry picked from commit db08361fda27c9858175e3a7f2e706e7bd850640)
=> Add Farm and Grower CRUD to documentation.

docs/files_endpoints.md, docs/files_sample_output.md, docs/operations_sample_output.md
*Added a disclaimer with units clarification
=> Units disclaimer

docs/files_endpoints.md, docs/operations_endpoints.md
Fixing some details on both Files and Field Operations Endpoints
=> solve the caca that I made this week

docs/files_sample_output.md
For this week, here are the features added to the live documentation.
- Maia: Added new properties for the file summary `operationDescription` 77cb8dc0ba9b9bca682a082d72f2dd88629c853d
=> Release 2.78.0  

docs/configurations_overview.md, docs/planet_overview.md, docs/release_notes.md, docs/satellite_overview.md, sidebars.js
The new release notes page: aa730e9faca42a940f4af30a71961c51481a20aa
Config adjustments: 735bab88e98c62f93074eb0daa75be0e679229a3
Small adjustments: 3bcc5559efed81691c5b0da70cac139d443a5d3d
=> Release notes page

docs/credentials_agleader.md, docs/credentials_cfv.md, docs/credentials_cnhi.md, docs/credentials_john_deere.md, docs/credentials_raven.md, docs/credentials_raven_slingshot.md, docs/credentials_stara.md, docs/credentials_trimble.md, docs/user_management_endpoints.md, sidebars.js
LeafUser endpoints reviewed: format and providers credentials pages
=> leaf-user-endpoints-review

docs/files_sample_output.md, docs/release_notes.md
new properties on the std geojson
=> 2.86.0-release-notes

docs/beta_prescriptions_endpoints.md, docs/field_boundaries_endpoints.md, docs/files_density_table.md, docs/files_endpoints.md, docs/files_overview.md, docs/operations_endpoints.md, docs/release_notes.md
=> Release 2.89.0

docs/alerts_endpoints.md, docs/files_endpoints.md
- Files upload 
- Create a webhook
- Delete a webhook
=> Python code examples review

docs/planet_overview.md, docs/release_notes.md, docs/satellite_overview.md, docs/sentinel_overview.md
Release notes page
Satellite, Planet, and Sentinel overview pages: updated to include NDRE references
=> Release notes - 2.91.0

docs/planet_overview.md, docs/release_notes.md
=> release-2.92.0

docs/credentials_john_deere.md, docs/planet_overview.md, docs/usecase_satellite.md, docs/usecase_upload.md, package-lock.json
Documentation review:
One-click auth - caf9d747e669abd12c853dcdbcea9a9bd14b4704
Planet file (bands) names - 5a20390c86a8c8303fedca6706a587256b7abe1b
Use cases review - a1146b36c15d75170c530f3be114c7dc401a828c and d852d160feae23d4b56cdf30fce999f2a5b82ce9
=> Doc review

docs/beta_layers_endpoints.md, docs/converters_endpoints.md, docs/converters_overview.md, docs/release_notes.md
- Layers upload endpoint - CFV
- Release notes
=> release-notes-2.100.0

docs/field_boundaries_endpoints.md
This PR is related to this (https://leafag.atlassian.net/jira/software/c/projects/SUP/boards/5?modal=detail&selectedIssue=SUP-17)[Jira item]
=> update fields response

docs/configurations_overview.md, docs/field_boundaries_endpoints.md, docs/files_crops_table.md, docs/operations_endpoints.md
- New configs: generateProviderImages and operationsProcessingRange
- Crop table updates - wheat dry moisture
- Grower name note
- cropOperationByField: fix the sample url
=> Release 2.102.0

docs/configurations_overview.md
operationsProcessingRange config - description review
=> Release text review

docs/files_endpoints.md
Description of the retry endpoint
=> retry-a-batch-upload

docs/files_endpoints.md
Added expected file structures for uploaded files
=> Add expected file structures for uploaded files

docs/files_endpoints.md
Review of the expected file structure by providers
=> Review of the expected file structure by providers

docs/configurations_endpoints.md, docs/configurations_overview.md, docs/sharedata.md
=> sharing-doc-review

docs/files_endpoints.md
Review of the status details messages from the batch upload endpoint
=> Batch upload errors

docs/files_sample_output.md, docs/operations_endpoints.md, docs/operations_sample_output.md, docs/release_notes.md, docs/satellite_endpoints.md
- singulation and downForce
- Satellite reprocess endpoint
=> Release notes 2.110.0

docs/operations_sample_output.md
Small spelling error fix for quatile to quantile.
=> fix spelling error

docs/credentials_stara.md
Removed developer note since the Field boundary integration is now available for Stara
=> stara-fields-availability

docs/release_notes.md
=> release-notes-2.113.0

docs/credentials_trimble.md, docs/widgets_file_upload.md
- Fix the Trimble credentials payloads
- Add requirements to Upload files widget page
=> Doc fixes trimble and widgets

docs/authentication.md
Change the order of text and formatting so that it flows step by step and reduces some duplication
=> Update authentication page

docs/beta_features_overview.md
- Grammar fixes
- More explicit information about layers including how to integrate Sentera first
- Split out prescription definition from Leaf's prescription service
=> Updates to beta overview page

docs/Link_endpoints.md
=> Link API key fix

docs/beta_assets_endpoints.md, docs/beta_features_overview.md, docs/operations_endpoints.md
Changes included in this release
-  Implements endpoint
-  Get files from an operation
=> Release 2 128 0

docs/Link_file_upload.md, docs/Link_provider_connection.md
Angular new version updates
New hook for uploading data
=> leaf-link-hooks-update

docs/field_boundary_management_endpoints.md, docs/machine_file_conversion_endpoints.md
- Uncovered files endpoint
- providerBoundaryId
=> Release 2.133.0

docs/configurations_overview.md, docs/field_boundary_management_endpoints.md, docs/machine_file_conversion_units.md
- Field boundary geometry automatic fix
- Field operations units normalization
=> Release notes 2.136.0

docs/irrigation_endpoints.md, docs/irrigation_overview.md, sidebars.js
Irrigation endpoints:
- Irrigation data
- Field irrigated
=> Irrigation data

docs/Link_endpoints.md, docs/credentials_valley.md, docs/field_boundary_management_upload_endpoints.md, docs/irrigation_endpoints.md, docs/provider-authentication-overview.md, sidebars.js
- Irrigation service
- Leaf authentication scopes
- Small documentation fixes
=> 2.143.0 - 2.144.0 release

docs/configurations_overview.md, docs/irrigation_endpoints.md
- Irrigation updates: new configuration, properties and endpoint
=> Release 2.146.0

docs/Link_file_upload.md, docs/Link_provider_connection.md
Language configuration for widgets
=> Widget locale property

docs/configurations_endpoints.md
=> Fix typo on Update configurations_endpoints.md

docs/configurations_overview.md
Configurations to enable/disable image generation
=> Operation image attributes configurations

docs/beta_assets_endpoints.md
Fixed the expected date format for filtering the assets endpoints
=> date parameter filter notes

docs/Link_endpoints.md, docs/Link_provider_connection.md, docs/field_boundary_management_endpoints.md
- New sync endpoint to enable preview fields based on the grower's list
- Stara app keys fixed for Link and Magic Link
=> New sync endpoint and Stara app keys updates

docs/configurations_overview.md
add the link to the manual sync endpoint
=> Custom data sync description

docs/Link_file_upload.md, docs/Link_provider_connection.md, docs/Magic_link_overview.md, docs/configurations_overview.md, sidebars.js
- Leaf Link/Magic Link out of beta
- Input Validator
=> Doc config adjusts

docs/alerts_authentication.md, docs/alerts_overview.md
Please review to ensure I haven't added anything inaccurate.
=> Alerts authentication and security

docs/machine_file_conversion_crops_table.md
https://github.com/Leaf-Agriculture/area-helper-lambda/blob/ba5768a440ca95bec99f1df3d513f6151c804d96/areahelper/tables/desired_moisture_table.json
=> Reconcile documentation with desire_crop_moisture_table
